routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Document\Http\Controllers\DocumentController;
use Document\Http\Controllers\DocumentCategoryController;
use Document\Http\Controllers\DocumentSettingsController;



Route::middleware('web')->group(function (){
    Route::middleware('auth_pacage')->group(function () {
        Route::group(['prefix'=>"admin", 'as'=>'admin.', 'middleware' => 'is_admin'],static function(){
            Route::resource('document',DocumentController::class);
            Route::group(['as'=>'document.','prefix'=>"documents"],static function(){
                Route::resource('category',DocumentCategoryController::class);
                Route::get('publish/{document}',[DocumentController::class,'publish'])->name('publish');
                Route::post('order',[DocumentController::class,'order'])->name('order');
                Route::post('category/order',[DocumentCategoryController::class,'order'])->name('category.order');
                Route::get('category/publish/{category}',[DocumentCategoryController::class,'publish'])->name('category.publish');
                Route::resource('settings',DocumentSettingsController::class);
            });
        });
    });
    try {
        $builder = new \Document\QueryBuilder\DocumentBuilder();
        $categories = $builder->getCategory();
        function setRouteDocument($categories,$url = ""){
            foreach ($categories as $category){
                if($category->url) {
                    $url = $url . "/" . $category->url;
                    Route::get($category->url . '/{document}', [DocumentCategoryController::class, 'getDocument']);
                    if ($category->parent instanceof Illuminate\Support\Collection)
                        setRouteDocument($category->parent, $url);
                }
            }
        }
        setRouteDocument($categories);
    } catch (Exception $exception) {
        
    }
});

resources/views/document/admin/category/create.blade.php
@extends('layouts.admin')
@section('title',"Документы")
@section('content')
    <div class="card">
        <x-admin.navigation :links="$links" />
        <x-admin.navigatin-js :links="$navigation" />
        <div class="card-body">
            <x-warning />
            <form action="{{ route('admin.document.category.store') }}" method="post" class="row row-page-create">
                @csrf
                <div class="tab-content">
                    <x-document::admin.category.create.content />
                    <x-document::admin.category.create.seo />
                </div>
                <div>
                    <input type="submit" value="Сохранить" class="btn btn-success btn-sm">
                </div>
            </form>
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.document.index")}}">Документы</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.document.category.index")}}">Категории</a></li>
            <li class="breadcrumb-item active" aria-current="page">Добавить</li>
        </ol>
    </div>
@endsection

resources/views/document/admin/category/edit.blade.php
@extends('layouts.admin')
@section('title',"Каталог")
@section('content')
    <div class="card">
        <x-admin.navigation :links="$links" />
        <x-admin.navigatin-js :links="$navigation" />
        <div class="card-body">
            <x-warning />
            <form action="{{ route('admin.document.category.update',['category'=>$category]) }}" method="post" class="row row-page-create">
                @csrf
                @method('PUT')
                <input type="hidden" value="{{$category->id}}" name="id">
                <div class="tab-content">
                    <x-document::admin.category.edit.content :category="$category" />
                    <x-document::admin.category.edit.seo :category="$category" />
                </div>
                <div>
                    <input type="submit" value="Сохранить" class="btn btn-success btn-sm">
                </div>
            </form>
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.document.index")}}">Документы</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.document.category.index")}}">Категории</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактировать</li>
        </ol>
    </div>
@endsection

resources/views/document/admin/category/index.blade.php
@extends('layouts.admin')
@section('title',"Документы")
@section('content')
    <div class="card">
        <x-admin.navigation :links="$links" />
        <div class="card-body">
            <div class="row row-page-create">
                <div class="col-md-8 order-md-first">
                    <div class="dd nestable" id="nestable">
                        <x-document::admin.category.list :categories="$categories" />
                    </div>
                </div>
                <div class="col-md-4 order-md-first d-flex align-items-start justify-content-end">
                    <a href="{{ route('admin.document.category.create') }}" class="btn btn-primary">Добавить категорию</a>
                </div>
            </div>

        </div>
    </div>
    <input type="hidden" id="route_dd" value="{{ route('admin.document.category.order') }}">
    <script src="{{ asset('assets/js/admin/dnd.js') }}"></script>
    <script src="{{ asset('assets/js/admin/delete.js') }}"></script>
    <script src="{{ asset('assets/js/admin/show.js') }}"></script>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.document.index")}}">Документы</a></li>
            <li class="breadcrumb-item active" aria-current="page">Категории</li>
        </ol>
    </div>
@endsection

resources/views/document/admin/document/create.blade.php
@extends('layouts.admin')
@section('title',"Документы")
@section('content')
    <div class="card" style="position: relative">
        <x-admin.navigation :links="$links" />
        <div class="card-body">
            <x-warning />
            <x-document::admin.document.crate />
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.document.index")}}">Документы</a></li>
            <li class="breadcrumb-item active" aria-current="page">Добавить</li>
        </ol>
    </div>
@endsection

resources/views/document/admin/document/edit.blade.php
@extends('layouts.admin')
@section('title',"Документы")
@section('content')
    <div class="card" style="position: relative">
        <x-admin.navigation :links="$links" />
        <div class="card-body">
            <x-warning />

            <x-document::admin.document.edit :document="$document" />
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.document.index")}}">Документы</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактировать</li>
        </ol>
    </div>
@endsection

resources/views/document/admin/document/index.blade.php
@extends('layouts.admin')
@section('title',"Документы")
@section('content')
    <div class="card" style="position: relative">
        <x-admin.navigation :links="$links" />
        <div class="d-flex justify-content-between" style="position: absolute;right: 10px;top: 10px;">
            <div>
{{--                <a data-id="1" data-name="text" class="btn btn-sm search modal-effect btn-warning badge" data-bs-effect="effect-fall" data-bs-toggle="modal" data-bs-target="#modaldemo8" type="button">Поиск</a>--}}

                <a href="{{ route('admin.document.create',['category'=>$category]) }}" class="btn btn-sm btn-outline-primary">
                    <small>Добавить позицию</small>
                </a>
            </div>
        </div>
        <div class="card-body">
            <x-document::admin.document.index :category="$category" />
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.document.index")}}">Документы</a></li>
            @if(!empty($breadcrumb) && count($breadcrumb)>0)
                @foreach($breadcrumb as $item)
                    @if(!$loop->last)
                        <li class="breadcrumb-item"><a href="{{$item['url']}}">{{$item['title']}}</a></li>
                    @else
                        <li class="breadcrumb-item active" aria-current="page">{{$item['title']}}</li>
                    @endif
                @endforeach
            @endif
        </ol>
    </div>
@endsection

resources/views/document/admin/settings/index.blade.php
@extends('layouts.admin')
@section('title',"Документы")
@section('content')
    <div class="card">
        <x-admin.navigation :links="$links" />
        <div class="card-body">
            <x-document::admin.settings />
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.document.index")}}">Документы</a></li>
            <li class="breadcrumb-item active" aria-current="page">Настройки</li>
        </ol>
    </div>
@endsection